"""Concurrent writers exercise clipboard lock/CAS semantics on private fixtures.

No test opens, inspects, or changes the user's Windows clipboard. Every clipboard
revision is generated by writes, not a mock returning a fixed sequence number.
"""
from contextlib import contextmanager
import threading
import pytest
from murmur import windows
from murmur.clipboard import decode_unicode, NativeClipboard
import ctypes
from types import SimpleNamespace


def unicode(text):return text.encode('utf-16-le')+b'\0\0'


class ClipboardFixture:
    MAX_BYTES=8*1024*1024
    TEXT_FORMATS=frozenset((1,7,13,16));UNICODE=13
    def __init__(self):
        self.lock=threading.Lock();self.lock_thread=None;self.open_owner=0
        self.values={1:b'original ANSI \x80\0',7:b'original OEM \x82\0',13:unicode('Original clipboard'),16:b'\x09\x04\0\0'}
        self.revision=1;self.actual_owner=900;self.pid_by_owner={900:90,777:70,1200:12,1300:13,1400:14}
        self.on_formats=None;self.on_replace=None;self.on_sequence=None;self.closed=threading.Event()
        self.mutations=0;self.fail_prepare=False;self.fail_next_replace=False;self.allocated=[]
    def _locked(self):assert self.lock_thread==threading.get_ident(), 'Clipboard read or write outside OpenClipboard'
    @contextmanager
    def opened(self,owner):
        if not self.lock.acquire(blocking=False):raise windows.ClipboardBusy('Synthetic clipboard lock contention')
        self.lock_thread=threading.get_ident();self.open_owner=owner;self.closed.clear()
        try:yield self
        finally:self.lock_thread=None;self.lock.release();self.closed.set()
    def sequence(self):
        self._locked()
        if self.on_sequence:callback=self.on_sequence;self.on_sequence=None;callback()
        return self.revision
    def owner(self):self._locked();return self.actual_owner
    def owner_pid(self,owner):self._locked();return self.pid_by_owner.get(owner,0)
    def formats(self):
        self._locked()
        if self.on_formats:callback=self.on_formats;self.on_formats=None;callback()
        return list(self.values)
    def data(self,format):self._locked();return bytes(self.values[format])
    def prepare(self,values):
        if self.fail_prepare:raise RuntimeError('Synthetic private allocation failure')
        result=[[format,bytes(data)] for format,data in values];self.allocated.extend(result);return result
    def replace(self,prepared):
        self._locked();self.values={};self.actual_owner=self.open_owner;self.revision+=1;self.mutations+=1
        for entry in prepared:
            self.values[entry[0]]=entry[1];entry[1]=None;self.revision+=1
            if self.on_replace:callback=self.on_replace;self.on_replace=None;callback()
            if self.fail_next_replace:self.fail_next_replace=False;raise RuntimeError('Synthetic SetClipboardData failure')
    def release(self,prepared):
        for entry in prepared:entry[1]=None
    def external_copy(self,text,owner=1400,delayed=False):
        if not self.lock.acquire(blocking=False):return False
        try:
            self.values={13:unicode(text)};self.actual_owner=owner
            if not delayed:self.revision+=2
            return True
        finally:self.lock.release()
    def text(self):return decode_unicode(self.values[13])


@pytest.fixture
def clipboard(monkeypatch):
    clipboard=ClipboardFixture()
    monkeypatch.setattr(windows,'_clipboard_backend',lambda:clipboard)
    monkeypatch.setattr(windows,'_clipboard_owner',lambda:777)
    # Any fallback to a Qt clipboard API would reopen the TOCTOU gap.
    monkeypatch.setattr(windows.QApplication,'clipboard',lambda:pytest.fail('Qt clipboard API must not be used'))
    return clipboard


def competing_writer(clipboard,text):
    """A second thread attempts a copy exactly inside a guarded transaction."""
    first_attempt=threading.Event();finished=threading.Event();attempts=[]
    def writer():
        attempts.append(clipboard.external_copy(text));first_attempt.set()
        assert clipboard.closed.wait(2)
        attempts.append(clipboard.external_copy(text));finished.set()
    def checkpoint():
        worker.start();assert first_attempt.wait(2)
        assert attempts==[False]  # OpenClipboard actively excluded the writer.
    worker=threading.Thread(target=writer)
    return checkpoint,worker,finished,attempts


def test_snapshot_cannot_mix_old_formats_with_concurrent_new_text(clipboard):
    original=dict(clipboard.values)
    checkpoint,writer,done,attempts=competing_writer(clipboard,'New copy during snapshot')
    clipboard.on_formats=checkpoint
    tx=windows.ClipboardTransaction();assert done.wait(2);writer.join(2)
    assert attempts==[False,True] and dict(tx.saved)==original
    assert clipboard.text()=='New copy during snapshot'
    before=clipboard.mutations
    with pytest.raises(RuntimeError,match='clipboard changed'):tx.write('Dictation result')
    assert clipboard.text()=='New copy during snapshot' and clipboard.mutations==before and tx.finished


def test_write_revision_cannot_be_stolen_by_copy_between_set_and_sequence(clipboard):
    tx=windows.ClipboardTransaction()
    checkpoint,writer,done,attempts=competing_writer(clipboard,'New copy just after write')
    clipboard.on_replace=checkpoint;tx.write('Dictation result')
    assert done.wait(2);writer.join(2)
    assert attempts==[False,True] and tx.sequence<clipboard.revision
    assert not tx.restore() and clipboard.text()=='New copy just after write'


def test_restore_comparison_and_replacement_exclude_concurrent_writer(clipboard):
    tx=windows.ClipboardTransaction();tx.write('Dictation result')
    checkpoint,writer,done,attempts=competing_writer(clipboard,'New copy during restoration')
    clipboard.on_sequence=checkpoint
    assert tx.restore();assert done.wait(2);writer.join(2)
    assert attempts==[False,True] and clipboard.text()=='New copy during restoration'
    assert not tx.restore()  # Does not retry after the user copied again.


def test_exact_text_formats_and_locale_round_trip_without_qt_conversion(clipboard):
    original=dict(clipboard.values);tx=windows.ClipboardTransaction();tx.write('Temporary MurMur text')
    assert clipboard.text()=='Temporary MurMur text' and tx.restore()
    assert clipboard.values==original and tx.restored and tx.finished
    assert all(entry[1] is None for entry in clipboard.allocated)


def test_new_delayed_copy_with_same_sequence_is_protected_by_owner(clipboard):
    tx=windows.ClipboardTransaction();tx.write('Temporary text');sequence=tx.sequence
    assert clipboard.external_copy('New delayed copy',delayed=True)
    assert clipboard.revision==sequence
    assert not tx.restore() and clipboard.text()=='New delayed copy'


def test_write_rejects_new_delayed_copy_between_snapshot_and_write(clipboard):
    tx=windows.ClipboardTransaction();sequence=clipboard.revision
    assert clipboard.external_copy('Delayed copy before write',delayed=True) and clipboard.revision==sequence
    with pytest.raises(RuntimeError,match='clipboard changed'):tx.write('Result')
    assert clipboard.text()=='Delayed copy before write' and not clipboard.mutations


@pytest.mark.parametrize('copy_again',[False,True])
def test_restore_busy_changes_no_state_and_retry_always_rechecks_cas(clipboard,copy_again):
    original=dict(clipboard.values);tx=windows.ClipboardTransaction();tx.write('Temporary text')
    assert clipboard.lock.acquire(blocking=False)
    try:
        with pytest.raises(windows.ClipboardBusy):tx.restore()
    finally:clipboard.lock.release()
    assert not tx.finished and not tx.restored and clipboard.text()=='Temporary text'
    if copy_again:
        assert clipboard.external_copy('Copied while restore was busy')
        assert not tx.restore() and clipboard.text()=='Copied while restore was busy'
    else:
        assert tx.restore() and clipboard.values==original
    assert tx.finished


def test_initial_snapshot_and_write_busy_never_mutate_existing_clipboard(clipboard):
    original=dict(clipboard.values);clipboard.lock.acquire()
    try:
        with pytest.raises(windows.ClipboardBusy):windows.ClipboardTransaction()
    finally:clipboard.lock.release()
    tx=windows.ClipboardTransaction();clipboard.lock.acquire()
    try:
        with pytest.raises(windows.ClipboardBusy):tx.write('Result')
    finally:clipboard.lock.release()
    assert clipboard.values==original and not clipboard.mutations and tx.finished


def test_copied_reads_owner_text_and_revision_in_same_lock_then_restores(clipboard):
    original=dict(clipboard.values);tx=windows.ClipboardTransaction();tx.write('')
    target=windows.Target(10,11,12,(42,1),13,True)
    assert clipboard.external_copy('Selection from target',owner=1200)
    snapshot=tx.copied(target);assert snapshot==(clipboard.revision,'Selection from target')
    assert tx.restore(snapshot[0]) and clipboard.values==original


def test_copied_cannot_mix_target_owner_with_concurrent_unrelated_text(clipboard):
    tx=windows.ClipboardTransaction();tx.write('');target=windows.Target(10,11,12,(42,1),13,True)
    assert clipboard.external_copy('Actual target selection',owner=1200)
    checkpoint,writer,done,attempts=competing_writer(clipboard,'Unrelated new copy')
    clipboard.on_formats=checkpoint;snapshot=tx.copied(target)
    assert done.wait(2);writer.join(2)
    assert snapshot[1]=='Actual target selection' and snapshot[0]<clipboard.revision
    assert attempts==[False,True] and not tx.restore(snapshot[0]) and clipboard.text()=='Unrelated new copy'


def test_copied_busy_is_distinct_and_preserves_pending_transaction(clipboard):
    tx=windows.ClipboardTransaction();tx.write('');target=windows.Target(10,11,12,(42,1),13,True)
    assert clipboard.external_copy('Selection',owner=1200);clipboard.lock.acquire()
    try:
        with pytest.raises(windows.ClipboardBusy):tx.copied(target)
    finally:clipboard.lock.release()
    assert not tx.finished and tx.copied(target)[1]=='Selection'


@pytest.mark.parametrize('owner,text',[(1400,'Unrelated owner'),(1200,''),(1200,' \t\n')])
def test_unrelated_or_empty_copy_cannot_authorize_restore(clipboard,owner,text):
    tx=windows.ClipboardTransaction();tx.write('');target=windows.Target(10,11,12,(42,1),13,True)
    assert clipboard.external_copy(text,owner=owner)
    assert tx.copied(target) is None
    assert not tx.restore(clipboard.revision) and clipboard.text()==text


def test_allocation_failure_occurs_before_empty_and_preserves_original(clipboard):
    original=dict(clipboard.values);tx=windows.ClipboardTransaction();clipboard.fail_prepare=True
    with pytest.raises(RuntimeError):tx.write('Result')
    assert clipboard.values==original and not clipboard.mutations


def test_partial_write_failure_rolls_back_under_same_lock(clipboard):
    original=dict(clipboard.values);tx=windows.ClipboardTransaction();clipboard.fail_next_replace=True
    with pytest.raises(RuntimeError,match='insertion failed'):tx.write('Result')
    assert clipboard.values==original and tx.finished and not tx.restored
    assert all(entry[1] is None for entry in clipboard.allocated)


def test_restore_allocation_failure_reports_fixed_error_instead_of_cas_false(clipboard):
    tx=windows.ClipboardTransaction();tx.write('Result');clipboard.fail_prepare=True
    with pytest.raises(RuntimeError,match='original clipboard could not be restored') as error:tx.restore()
    assert 'private' not in str(error.value) and tx.finished and clipboard.text()=='Result'


def test_rich_format_snapshot_is_refused_without_reading_or_writing(clipboard):
    clipboard.values[99999]=b'Synthetic rich payload'
    with pytest.raises(RuntimeError,match='rich content'):windows.ClipboardTransaction()
    assert not clipboard.mutations


def test_native_owner_accepts_legal_null_and_clears_stale_last_error():
    native=NativeClipboard.__new__(NativeClipboard)
    native.user=SimpleNamespace(GetClipboardOwner=lambda:None)
    native.api=SimpleNamespace(GetClipboardOwner=lambda:pytest.fail('pywin32 null-owner wrapper must not be used'))
    ctypes.set_last_error(5)
    assert native.owner()==0 and ctypes.get_last_error()==0


def test_native_owner_retains_real_owner_and_rejects_actual_access_error():
    native=NativeClipboard.__new__(NativeClipboard)
    native.user=SimpleNamespace(GetClipboardOwner=lambda:777)
    assert native.owner()==777
    def failed():ctypes.set_last_error(5);return None
    native.user.GetClipboardOwner=failed
    with pytest.raises(RuntimeError,match='owner could not be verified'):native.owner()


def test_unowned_clipboard_snapshot_write_restore_round_trip(clipboard):
    original=dict(clipboard.values);clipboard.actual_owner=0
    tx=windows.ClipboardTransaction()
    assert tx.initial_owner==0
    tx.write('Result inserted from unowned clipboard')
    assert tx.restore() and clipboard.values==original and tx.restored


def test_zero_owner_is_valid_for_atomic_cas_but_new_unowned_content_is_preserved(clipboard):
    clipboard.actual_owner=0;tx=windows.ClipboardTransaction()
    assert clipboard.external_copy('New unowned clipboard',owner=0)
    before=clipboard.mutations
    with pytest.raises(RuntimeError,match='clipboard changed'):tx.write('Result')
    assert clipboard.text()=='New unowned clipboard' and clipboard.mutations==before
